### ISSUE TITLE
DD # 1

### ISSUE THREAD

**Issue by gorterd** [troubadour10/Blackbird#1]
Great design docs so far, Mark! Here’s my feedback for MVPs and DB schema; checkmarks are for should-do’s, and regular bullets are for other suggestions / comments:

**MVP LIST**
- Dashboard
  - Since the news stories would likely require using an external API, consider possibly moving this to a bonus feature
  - [x] In addition to the chart, I’d add that a user can see their ‘Stocks’ list here (in the sidebar above watchlists: all the stocks the user owns) 
- Asset Detail
  - I’d provide more specificity regarding options for buying and selling stock depending on how much of the Robinhood UI you want to implement: seeing your buying power & being able to invest in either dollars or shares are the main relevant ones (I would suggest leaving multiple order types as a bonus / not do that at all though)
  - There’s some info boxes with your current market value in a stock you have, including today’s return and total return; up to you if you want to implement that, but if you do, I’d add that as a bullet 
- Watchlist: 
  - [x] add where users can add/remove companies (from their asset detail page?)
  - [x] Can users create multiple lists? If so, in addition to the CRUD of adding stocks to / removing them from the list, you should add that users are able to create and destroy lists
- Search: The actual search on Robinhood gives live updated search results as you type - I’d mention that specifically as it’s something to think about how to implement going into that MVP

**SCHEMA**
- Users: if account_value simply refers to the total value of one’s portfolio, I’d suggest leaving that off as a column since it could be derived from the total value of all the shares owned by a user
- Watchlists: 
  - [x] Add a column for a watchlist name / title if you want to allow users to create multiple watchlists and name their watchlists 
  - [x] I’d suggest removing the foreign key of company, since one watchlist could have many companies in it; instead, I’d suggest having a joins table that joins companies and watchlists
- [x] Shares_owned: transaction foreign key not necessary, since multiple transactions contribute to a single portfolio / set of owned shares --> there’s no one transaction you could point to
- [x] Transactions: 
  - [ ] You’ll have a lot of null values if you have separate buy/sell columns; instead, I’d suggest just having a price colum, and a type column that points to either buy or sell
  - Following this, buy / sell timestamps not necessary, since presumably it would be the same as the created_at column (you’d create the transaction record in the db whenever it happened)
  - You might not need the transactions table at all, though I’m curious how you were going to use it (you can just update shares owned whenever a transaction is made) if you have no need to view, for instance, someone’s transaction history)

**Comment by mcamilleri10** [comment]
Thank you for this feedback Daniel - super helpful! Just finished up my revisions.

**Comment by mcamilleri10** [comment]
I also revised my sample state to reflect those changes, and added a few things that were missing.

**Comment by gorterd** [comment]
Nice work on the revisions! Two small things: (1) I forgot to mention in the first review, but you'd probably want some uniqueness constraints on the combo of user and company for shares_owned, and for the combo of watchlist and company for watchlist_companies_joins. (2) not a huge deal, but naming convention I've seen for joins tables might be more like `watchlist_companies` or `company_watchlists` (not using the actual word 'joins'); just an fyi, how you name your tables is your choice of course!

**Comment by mcamilleri10** [comment]
got it, just finished those up.
and in answering your initial curiosity on how i was going to use the transactions table  - i figured i needed to keep track of the buy price as that would be needed to be able to display the cost basis & gain for the owned shares
