### ISSUE TITLE
DD #3 Frontend Routes & Components

### ISSUE THREAD

**Issue by gorterd** [troubadour10/Blackbird#3]
Great work, Mark! Let me know if you have questions about this or any of the other feedback I provided on your docs. As always, take or leave my feedback, the ultimate design choices are yours!

**Feedback**
- The NavBar that appears on the splash page looks pretty different from the one that appears when logged in. They could still be the same component with a bunch of conditional logic, but you might also consider making them different components. 
- the Footer only appears on the splash page (the components up top are the ones that always render no matter what)
- there is no NavBar on the signup or login pages for me, so the NavBar might need to be moved out of  the top as well. 
  - because of this, that means that many, but not all, routes render the same NavBar. You could have each route render its own NavBar, but that would involve re-mounting that component each time (not the most efficient, but not a huge deal for an app of this scale). You could also nest everything that shares the logged in navbar under a common parent route. That route could render the Navbar, and then have child routes that render all the different logged in pages.
- you might consider nesting the ShareIndex & Watchlist components under a shared sidebar container component on the user show page.
 - you might want to have a separate component just for search within the NavBar (which might sometimes render search results, which again could be their own subcomponent of search).

**Comment by mcamilleri10** [comment]
Thanks Daniel - I really like all of these suggestions.  I'm not sure exactly how to structure the nested navbar routes - please let me know what you think
