### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by gorterd** [troubadour10/Blackbird#4]
Excellent work, Mark!

Feedback:
- [x] You shouldn't have any dead links or anything that implies the presence of a feature you haven't implemented. This means the Products and Learn dropdowns in your NavBar should be refactored. I'd suggest replacing those with links to your github, personal website, linkedin etc.
  - no need to keep those as dropdowns, but if you do, clicking outside the dropdown should close the dropdown
- [x] You should change all the text that implies your clone actually involves financial transactions (eg. the Commissions disclosure). Have fun with what it says instead! Might be a nice touch to customize all the text a bit (on splash page, the text on the right on the sign up page, etc)
- [x] Error messages don't clear. After attempting to sign up and then going to log in page, I see this: ![Login Page](https://i.imgur.com/3GKdrGs.png)
- [x] Add hover effect to `Sign in` and `Continue` buttons so they get darker upon hover
- [ ] don't spend more than an hour on this, but I'd suggest handling some of the input validation in the signup form on the frontend, before the user submits the form  (e.g. in Robinhood, upon leaving the password field, if it isn't minimum of ten character, the corresponding error appears). using an onBlur event handler would probably be the place to start. you might also want to use built in HTML email validation (which is what robinhood appears to use), which gets checked upon clicking the form submission button - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email#Validation

**Comment by mcamilleri10** [comment]
Okay I fixed almost everything up.
- I added some humor to a lot of the text, let me know if you think it's too unprofessional
- I tried for a bit over an hour on the password error rendering and came up short. I'll come back to it when I've made more progress on my other mvps.

**Comment by mcamilleri10** [comment]
(if that is okay)

**Comment by gorterd** [comment]
Looks amazing, keep it up!
