### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by gorterd** [troubadour10/Blackbird#5]
Great work Mark! Fantastic styling and great implementation of Recharts. Functionality is also great. Most of my feedback under the functionality header involves nice-to-haves that would (mostly) be difficult to implement and thus I've left as optional / bonus. 

**Functionality**
- [x] Until you finish the CRUD for shares, I might give new users a free share of something (one idea — using after_create callback for the user model). Right now I get this: ![](https://i.imgur.com/q6Jt6w5.png)
- Optional / Bonus: Instead of a logout button, make it an account dropdown like in Robinhood (in your case, would probably only include name, portfolio value / buying power, and logout)
- Optional / Bonus: adjust the time zone for the graph to the user's local time zone. 
- Optional / Bonus: We talked about how it's fine to omit this earlier, but I think if you have time, it would be nice for your portfolio value in the upper left of the graph to adjust as you hover over the graph. I took a look at the Recharts api and saw some event handlers you can put on Lines / LineCharts, but haven't tested it out yet -- I might try to if I have time.
- Optional / Bonus: I noticed there is sometimes quite a delay between clicking on a different timeframe and the resulting graph to render. Might not be much you can do about it if it's just how long the API request takes, but I'd consider, if it's feasible, fetching the data for all time frames immediately upon mount of the Dashboard, so that switching is faster. Alternatively, as a bonus, I might consider some kind of loading animation. 

**Styling**
- [x] Noticed on your splash -- page is very tall and extends way past the footer for some reason
- [x] Add hover effect to search result items (also, optional --> I'd make the clickable region larger, not just the text (in other words, there shouldn't be gaps between search results where I can't click)
- [x] This happens (consider using the `overflow` css property on the sidebar div) ![](https://i.imgur.com/mgxeBDO.png)
- [x] Very small thing, but I'd remove the semicolon from the date / time / price when hovering over the graph, and would format the date time to be like Robinhood (eg Sept 28, 1:00 PM instead of 2020-09-28, 13:00)
- [x] I'd remove the grey border under the Buy Power box when it is expanded (You could probably just use a ternary to change the class name depending on whether it is expanded / collapsed, only have a border bottom when it's collapsed)
- [x] I realize customizing Recharts graphs is pretty difficult, but I think it would be doable/worthwhile, when hovering over the graph, for the date / time to appear at the top of the line instead of by the cursor. Not sure what your code looks like, but [this may be helpful](https://github.com/recharts/recharts/issues/1848#issuecomment-542341898).

**Comment by mcamilleri10** [comment]
Thank you for the recharts link!! Position is not even a property for tooltip in their own docs!

**Comment by mcamilleri10** [comment]
addressed everything including a loading animation for the graph when changing date ranges. hoping i can finish my asset mvp early enough tomorrow to go back to a few of the bonuses.

**Comment by gorterd** [comment]
Nice, looks great! One small thing: the sidebar overflow is working for me, but I might consider using auto as a value instead of scroll (assuming that's what you used). Essentially with overflow: scroll, if you're using a mouse (which I am now), you'll always see scrollbars, even when there's not enough content to need scrolling.
